---
- hosts: all
  gather_facts: False
  tasks:
    - name: Get hostname
      command: hostname
      register: hostname_result
    
    - name: Debug hostname
      debug:
       var: hostname_result.stdout
       
    - name: update packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      register: update_result
    
    - name: Setup NodeSource repository and install Node.js
      become: yes
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash -
        sudo apt-get install -y nodejs
      register: nodejs_result