---
- hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Get hostname
      command: hostname
      register: hostname_result
    
    - name: Debug hostname
      debug:
       var: hostname_result.stdout
       
    - name: update packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
      register: update_result
    
    - name: install nodejs 20.13 using nvm
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
        source ~/.bashrc
        nvm install 20
      register: nodejs_result
    
    - name: Debug nodejs
      debug:
        var: nodejs_result.stdout
        